### PR TITLE
Create analysis prop select one

### PR DESCRIPTION
**Pull request by yannsay-impact**

### CODE REVIEW

**Comment by yannsay-impact** [comment]
[calculate proportion - select one](https://trello.com/c/BuyVUl04/81-calculate-proportion-select-one)

**Comment by mhkhan27** [comment]
Hey I think we should rename the functions to create_analysis_xxx_from_dap and make a new function for `without_dap`. I dont think most of the people make dap these days. So we probably should focus on both.

**Comment by mhkhan27** [comment]
I belive its also better if we split the group_var and group_var_value so the use can filter the result easily. 
image

**Comment by mhkhan27** [comment]
If I accidentally provide multiple inputs in dap. However, it's not showing any error or warning messages(as it always takes the first one). I made this mistake, I initially thought dap is a data frame (which was stupid!) but I am sure there are some other who might be making the same mistake.  
image

**Comment by yannsay-impact** [comment]
- I have replace dap argument by group_var, analysis_var and level. I think next step will have something to apply over those functions with and without a dap.

- I would like to keep the group_var and group_var_value as one column with a predictable name, as it would be change based on the number of variables for the groups, or name of the variable. At least for the results, I would prefer to have the function to separate those in the presentresults package.

- I think by changing the arguments (dap vs group_var, analysis_var and level), it solved the issue you raised.

```
set.seed(1222)
somedata <- data.frame(
  group_a = sample(c("group_value_a", "group_value_b"), 50, replace = T),
  group_b = sample(c(
    "group_value_2_aa", "group_value_2_bb"
  ), 50, replace = T),
  group_c = sample(c(
    "group_value_3_aaa", "group_value_3_bbb"
  ), 50, replace = T),
  value = rnorm(100, mean = 20, sd = 10)
)


dap_mean <- c(group_var = "group_a", "group_a, group_b", "group_a, group_b",
              analysis_var = "value", "value", "value",
              level = 0.95, 0.95, 0.95)

create_analysis_mean(srvyr::as_survey(somedata), dap_mean)
create_analysis_mean(srvyr::as_survey(somedata), 
                     group_var = c("group_a", "group_a, group_b", "group_a, group_b"),
                     analysis_var = c("value", "value", "value"),
                     level = c(0.95, 0.95, 0.95))

```

image

**Pull request merged**
